service: sls-mongodb-demo
useDotenv: true
frameworkVersion: "2"

custom:
  localstack:
    debug: true
    stages:
      - local
      - dev
    endpointFile: localstack_endpoints.json

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: nodejs14.x
  region: ap-south-1
  lambdaHashingVersion: 20201221

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-localstack

functions:
  collections:
    handler: api/collections.manage
    events:
      - http:
          path: collection
          method: post
          cors: true
