service: sls-mongodb-demo
useDotenv: true
frameworkVersion: "2"

custom:
  localstack:
    debug: true
    stages:
      - local
      - dev
    endpointFile: localstack_endpoints.json

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: nodejs14.x
  region: ap-south-1
  lambdaHashingVersion: 20201221

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-localstack

functions:
  pgCreate:
    handler: apis/pgApiHandler.create
    events:
      - http:
          path: pgTodos
          method: post
          cors: true
  create:
    handler: apis/apiHandler.create
    events:
      - http:
          path: todos
          method: post
          cors: true

  getOne:
    handler: apis/apiHandler.getOne
    events:
      - http:
          path: todos/{id}
          method: get
          cors: true

  getAll:
    handler: apis/apiHandler.getAll
    events:
      - http:
          path: todos
          method: get
          cors: true

  update:
    handler: apis/apiHandler.update
    events:
      - http:
          path: todos/{id}
          method: put
          cors: true

  delete:
    handler: apis/apiHandler.delete
    events:
      - http:
          path: todos/{id}
          method: delete
          cors: true
